### ISSUE TITLE
New secret doors show outlines

### ISSUE THREAD

**Issue by Everturning** [new-frontiers-14/frontier-station-14#1016]
## Description
New secret doors, such as the wooden wall door, momentarily show a green outline, revealing it to be a secret door. This can cause issues with metagaming, because even if we're MRP, we still have metagamers.

**Reproduction**
make any new secret wall
mouse over it
momentarily see green outline

**Screenshots**

**Additional context**

**Comment by ErhardSteinhauer** [comment]
Couldn't reproduce:
https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/49b0475c-1b40-4f00-a4a1-366dca7657a3

**Comment by Everturning** [comment]
> Couldn't reproduce: https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/49b0475c-1b40-4f00-a4a1-366dca7657a3

When it happened for me I was walking. Maybe something to do with that?

**Comment by ErhardSteinhauer** [comment]
No dice still
https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/31e07f2f-b7c3-49f5-ad92-5b3668f8b9c7

**Comment by Everturning** [comment]
huh weird
