### ISSUE TITLE
Alert levels are not in sync on other ships

### ISSUE THREAD

**Issue by Myzumi** [new-frontiers-14/frontier-station-14#1139]
## Description

Alert levels seems to be different on each ship you are and do not follow station alerts

**Reproduction**

- Get a ship
- Increase alert on station to Blue
- See that station is in blue alert, even on the PDA
- Go on the ship
- See that the ship is in green alert, even on the PDA

**Screenshots**

![image](https://github.com/new-frontiers-14/frontier-station-14/assets/34660019/6c4fe7bb-eba4-4078-8fc1-aaa1d265128f)
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/34660019/569d9a10-c6e2-48a1-9346-634d16f05c10)

**Additional context**

**Comment by whatston3** [comment]
System being added in #1513 that can help address this (system-wide services).  Needs a separate feature to swap over how the alert status is read in and stored.
