### ISSUE TITLE
Vulpkanin Scream Sounds are unlicensed (Maybe more)

### ISSUE THREAD

**Issue by PursuitInAshes** [new-frontiers-14/frontier-station-14#1199]
## Description
Not a player facing issue, but a repo based one. The audio files don't have a license or attribution attached to them, could be problematic in the future.

**Reproduction**
Search the repo for "scream1.ogg" and you won't find any attribution or license file.

**Comment by dvir001** [comment]
We have the DeltaV ones.
They have the attribution or license files mentioned, we need to add them here also.

**Comment by dvir001** [comment]
Ok we didnt have the DeltaV one and this was a fuck up, I fixed it with the goblin PR
