### ISSUE TITLE
[Mega-issue] List of NFSD ships for resprite

### ISSUE THREAD

**Issue by ThatOneGoblin25** [new-frontiers-14/frontier-station-14#1230]
With new airlocks, lockers, jetpacks, dressers, barriers and more from #1064, #1183 and #1205. NFSD ships now need new PRs that update the decals, lockers, airlocks etc. Ideally people could just change the prototypes in the yml and check it out in `mapping` to confirm. Please also move the ymls into `/_NF/Security` which haven't already been relocated and update the shipyard's `mapPath`. Also please include a screenshot of the ship in your PR for the wiki.

A checkbox can be ticked if the resprite PR has been successfully merged. It will then be linked.
Please mention this issue in ship PR's, as this automates a lot of this.

NFSD Shipyard :

- [x] NSF Empress (https://github.com/new-frontiers-14/frontier-station-14/pull/1243)
- [x] NSF Cleric (https://github.com/new-frontiers-14/frontier-station-14/pull/1243)
- [x] NSF Fighter (https://github.com/new-frontiers-14/frontier-station-14/pull/1243)
- [x] NSF Rogue (https://github.com/new-frontiers-14/frontier-station-14/pull/1243)
- [x] NSF Marauder
- [x] NSF Wasp (https://github.com/new-frontiers-14/frontier-station-14/pull/1259)
- [ ] NSF Opportunity?
- [x] NSF Prowler (https://github.com/new-frontiers-14/frontier-station-14/pull/1254)
- [x] NSF Whisky (https://github.com/new-frontiers-14/frontier-station-14/pull/1253)
- [x] NSF Inquisitor (https://github.com/new-frontiers-14/frontier-station-14/pull/1251)
- [x] NSF Interceptor (https://github.com/new-frontiers-14/frontier-station-14/pull/1245)
- [x] NSF Hospitaller (https://github.com/new-frontiers-14/frontier-station-14/pull/1239)
- [x] NSF Templar (https://github.com/new-frontiers-14/frontier-station-14/pull/1239)

POI:

- [x] NSFD outpost (https://github.com/new-frontiers-14/frontier-station-14/pull/1274)

~~Expedition procedurals?~~

**Comment by dvir001** [comment]
Expedition tileset isn't changing since lore wise security still exists as an entity in the universe.

**Comment by Kesiath** [comment]
I plan to do a full Marauder rework, and to alter the Prowler, Templar, and Hospitaller to reflect the new changes.

**Comment by dvir001** [comment]
Add more M_EMP to ships

**Comment by Tych0theSynth** [comment]
I'll look into doing the Interceptor, Rogue and Fighter in the coming days.

**Comment by Gotimanga** [comment]
I plan to work on updating the Wasp

**Comment by dvir001** [comment]
@Tych0theSynth Keep in mind when we update master with upstream you can do mini updates to replace mapped buttons to locked security versions ones if you need them.

@Gotimanga Add late join prisoner's spawners to the cells area and move the normal latejoin spawner to main area, we have code to allow prisoners to spawn on dedicated spawners but we could have not used it till now since the ship was missing the late join for them.

**Comment by dvir001** [comment]
Going to close is since Opportunity will come back with recolor when it comes back anyway.
