### ISSUE TITLE
Mass scanner labels incorrect at higher UI scales

### ISSUE THREAD

**Issue by avosirenfal** [new-frontiers-14/frontier-station-14#1337]
## Description
With my UI scale set to 150% the labels in the mass scanner UI are incorrectly positioned.

**Reproduction**
1. Set your UI scale in graphics to 150%
2. View the mass scanner
3. The labels are translated to incorrect positions

**Screenshots**
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/2704742/97f97e9a-e135-44ef-8dc2-9f78828090f4)

**Additional context**
This is very frustrating, it's difficult to play with a small UI on my monitor but the map is functionally useless at times because of overlapping labels.

**Comment by exincore** [comment]
Seems to be (re)introduced in 6a1e1e2
