### ISSUE TITLE
If you get more than 2^31 spesos you kill the server

### ISSUE THREAD

**Issue by user424242420** [new-frontiers-14/frontier-station-14#1354]
## Description

Its because you use int type of data, not ulong 

**Reproduction**

Get more than 2^31

**Screenshots**

**Additional context**

I fix it in local build with this pr https://github.com/Corvax-Frontier/corvax-frontier-14/pull/152

**Comment by dvir001** [comment]
Why was this PR closed there?

**Comment by user424242420** [comment]
> Why was this PR closed there?

Because they wait for your upstream 🤡

**Comment by user424242420** [comment]
@dvir001 Closed due pr with fixing this problem https://github.com/new-frontiers-14/frontier-station-14/pull/1355
