### ISSUE TITLE
Hotplate machine missing circuitboard research unlock

### ISSUE THREAD

**Issue by AJimmyU** [new-frontiers-14/frontier-station-14#1356]
## Description

Hotplate, a machine used to heat up beakers for chemistry, is missing a research entry for the relevant circuitboard.

**Reproduction**

1. research all techs
2. try to build a chem lab

**Screenshots**

**Additional context**

All other chemistry machines are researchable, except hotplate.

**Comment by dvir001** [comment]
Will be fixed in coming update
