### ISSUE TITLE
Dragons when butchered delete all inside of them

### ISSUE THREAD

**Issue by Leander-0** [new-frontiers-14/frontier-station-14#1397]
## Description
Title, when the carp dungeon boss the dragon is taken by a player they have the ability to devour people in dead or critical condition, this becomes an issue since you expect that if the dragon ate someone it should release them once you butcher the dragon but thats not the case and instead whatever they devoured it gets deleted.

This becomes more of an issue if the captain of the ship gets devoured along with his ID that they used to buy the ship with.

**Reproduction**

Go to expedition with a crew, someone dies to a dragon ghost role and gets devoured, when the crew tries to rescue them after killing the dragon they are gone forever.

**Comment by ErhardSteinhauer** [comment]
https://github.com/space-wizards/space-station-14/pull/28709
