### ISSUE TITLE
Pirate Latejoin is broken

### ISSUE THREAD

**Issue by Leander-0** [new-frontiers-14/frontier-station-14#1433]
## Description

Any pirates that spawn on the pirate cove dont start with bank component and so they cannot buy any ships or deposit money.

**Reproduction**

Latejoin spawn as pirate captain or first mate on the pirate cove, same applies for the regular pirates that spawn on the pirate ships.

**Comment by dvir001** [comment]
https://github.com/new-frontiers-14/frontier-station-14/pull/1422
