### ISSUE TITLE
There's a problem

### ISSUE THREAD

**Issue by QFci** [new-frontiers-14/frontier-station-14#1455]
## Issues with download (or maybe i dont know how)

**Screenshot of console**

![image](https://github.com/new-frontiers-14/frontier-station-14/assets/170968320/328b0f8a-3817-49d1-b84b-a7d309ba582f)

**Anybody know how to download?**

**Comment by LordJike** [comment]
I don't think this is the correct place for such things but uhh... Maybe try following this advice? 

https://stackoverflow.com/questions/59282476/error-rpc-failed-curl-92-http-2-stream-0-was-not-closed-cleanly-protocol-erro
