### ISSUE TITLE
Hover Bike if used in space with a weapon, recoil will cause you to get unbuckled.

### ISSUE THREAD

**Issue by Qulibly** [new-frontiers-14/frontier-station-14#1481]
## Description

Whenever you use a firearm while riding a hoverbike in space. It's recoil will start to move you away. If you are static while firing you will float away till reaching max distance of buckle and in result get unbuckled.
If you start moving while firing you will jitter alot and possibly soon get unbuckled

**Reproduction**

- Get a hoverbike
- Buckle onto it
- Grab a weapon in other hand (in this case PKA)
- Move hoverbike into space (not on any tiles)
- Stand still while on hoverbike and buckled
- Fire weapon (PKA) in any direction
- Observe as your character is slowly floating away from recoil of the short
- You will eventually get unbuckled when you drift too far from the bike

**Additional context**

Only noticed it in space. It might possibly also happen when on grid without gravity active. Needs testing

**Comment by dvir001** [comment]
Upstream

**Comment by Qulibly** [comment]
> Upstream

Dang, I hoped it was on our side :<

**Comment by whatston3** [comment]
Fix is here: https://github.com/new-frontiers-14/frontier-station-14/pull/1679/commits/d426355749e6ca304e24a3d2d3634f31fe6c083c

Should be applied in the July upstream merge unless reverted.

**Comment by ZombieChibiXD** [comment]
can be closed?
