### ISSUE TITLE
Contraband status obfuscated from players

### ISSUE THREAD

**Issue by AJimmyU** [new-frontiers-14/frontier-station-14#1507]
## Description
Items that can be sold as contraband at NFSD outpost are only knowable by trial and error. There's no in character method of figuring out whether something is actually worth dragging to NFSD for sale without code diving for contraband component.

There's often no relation between item description and actual contraband status from game perspective.

**Reproduction**

1. Examine blood-red magboots
2. No mention of contraband status
3. Sells for 1 FUC

Second example

1. Examine atreides SMG
2. `often used by Syndicate agents`
3. Is not actually valid contraband for sale

**Screenshots**

**Additional context**

Either an automatic mention on examine or a contraband scanner akin to price scanner could be implemented.

Or manually adjusting all items that have `contraband` component to have an examine description mentioning this fact, while items that do not have it should not imply they are contraband.

**Comment by dvir001** [comment]
Funny thing I have code to fix this issue,
This to redo it and PR.

**Comment by dvir001** [comment]
https://github.com/new-frontiers-14/frontier-station-14/pull/1509/files
