### ISSUE TITLE
NFSD To Nfsd

### ISSUE THREAD

**Issue by dvir001** [new-frontiers-14/frontier-station-14#1511]
## Description
NFSDCriminalRecordsComputerCircuitboard
NFSDAdvancedRadarConsoleCircuitboard
SignDirectionalNFSD
DefaultStationBeaconFrontierNFSD
DefaultStationBeaconFrontierNFSDBrig

Need a rename to match the same format on the rest of the code base.

**Comment by whatston3** [comment]
Marginally related - now apply the "proper name capitalization in names/descriptors" issue to NFSD entity. :eyes:

**Comment by Salvantrix** [comment]
I feel attacked, will look at it on Tuesday.

**Comment by dvir001** [comment]
> I feel attacked, will look at it on Tuesday.

You should feel attacked
Thanks.

**Comment by dvir001** [comment]
Fixed
