### ISSUE TITLE
Cannot open crew slots

### ISSUE THREAD

**Issue by Rhentin** [new-frontiers-14/frontier-station-14#1600]
## Description

So, as pirate earlier in the day, I purchased a Bocadillo, and could not open crew slots, in fact the entire "Crew Records" console was blank, with no entries whatsoever. I did notice something similar on several other ships as well.
**Reproduction**

Buy a bocadillo.
**Screenshots**

I didn't think to take any when I was playing.
**Additional context**

I don't think there's much to say, other than having to Ahelp for something, though in this case the Ahelp didn't open any crew slots for me.

**Comment by whatston3** [comment]
Resolved with https://github.com/new-frontiers-14/frontier-station-14/pull/1664.
