### ISSUE TITLE
LoneOpsSpawn Gamerule activating by itself through EventScheduler

### ISSUE THREAD

**Issue by Qulibly** [new-frontiers-14/frontier-station-14#1632]
## Description

Lone Op gamerule is activating by itself during Frontier round which has high chance to cause serious issues. 

**Reproduction**

From what found so far through checking seems to be activated by event scheduler when it "rolls" on it.
More checking might be needed.

**Screenshots**

Don't have any screenshots that could assist sadly

**Additional context**

Has been noticed multiple times through the rounds when checking list of active gamerules

**Comment by ErhardSteinhauer** [comment]
https://github.com/new-frontiers-14/frontier-station-14/pull/1589

**Comment by whatston3** [comment]
Just following up - should be resolved, but hasn't yet been pulled into the server.  Sorry about the bug, lack of thoroughness on my part during the june upstream merge.
