### ISSUE TITLE
Maildrobe Ads Broken

### ISSUE THREAD

**Issue by potato1234x** [new-frontiers-14/frontier-station-14#165]
## Description

sometimes the maildrobe says "advertisement-maildrobe-1"
**Reproduction**

watch a maildrobe
**Additional context**

ftl file broked

**Comment by dvir001** [comment]
Ill probably add it, thanks for the report
https://github.com/Nyanotrasen/Nyanotrasen/blob/79f4db993d0f3f98dc61b352e78b718de0164b9c/Resources/Locale/en-US/advertisements/vending/maildrobe.ftl#L2

**Comment by Cheackraze** [comment]
syndie drobe is also missing adverts i think, not sure how we didn't get those because that was an upstream commit

**Comment by dvir001** [comment]
> syndie drobe is also missing adverts i think, not sure how we didn't get those because that was an upstream commit

https://github.com/space-wizards/space-station-14/blob/25976688917eec1689138460655a23fe01477f1e/Resources/Locale/en-US/advertisements/vending/syndiedrobe.ftl
