### ISSUE TITLE
Panic Bunker's "Connection Denied" message doesn't properly display the hours needed to bypass it

### ISSUE THREAD

**Issue by FernandoJ8** [new-frontiers-14/frontier-station-14#1651]
## Description

An image will be worth a thousand words here, but the amount of hours needed to ignore panic bunker are not correctly displayed on the disconnect message that you're given when you fail to join. It says "{$hours}" instead.

**Reproduction**

Attempt to join the server while panic bunker is on and without meeting the playtime requirement to bypass it.

**Screenshots**

![image](https://github.com/new-frontiers-14/frontier-station-14/assets/80640114/aebf3f1d-8d99-4616-abe5-91ead056e664)

**Additional context**
N/A

**Comment by whatston3** [comment]
Upstream issue, will be resolved with #1679.

**Comment by whatston3** [comment]
Forgot to resolve this.  Should be fixed.
