### ISSUE TITLE
Contraband Clothing faction makes syndies friendly

### ISSUE THREAD

**Issue by Ed-Head** [new-frontiers-14/frontier-station-14#1656]
## Description

The contraband clothing faction gets added to NPCs wearing contraband clothing i.e all the syndies on expeds, events, and LPB. This means any player who gets added to that faction is de-facto besties with said syndies while they wear it. The only thing syndie thing that still attacks in my finding are turrets as they don't wear anything I guess. 

**Reproduction**

Go to a place with syndies like lpb, put on a syndie gasmask and watch in awe as they stop filling you with bullets.

**Screenshots**

![bug1](https://github.com/user-attachments/assets/130eba2f-6f1e-4cc6-ad7c-91b1a6634893)
![bug2](https://github.com/user-attachments/assets/d44e7d45-ba97-4ecb-8231-49bc14d1ad03)
![bug3](https://github.com/user-attachments/assets/be36f234-c5d5-4607-a936-1abf0d021962)

**Additional context**

**Comment by ErhardSteinhauer** [comment]
Solved with [this PR](https://github.com/new-frontiers-14/frontier-station-14/pull/1659)
