### ISSUE TITLE
Jugs in chemvend appear unlabeled

### ISSUE THREAD

**Issue by Ghagliiarghii** [new-frontiers-14/frontier-station-14#1682]
## Description

Items in vending machines with labels applied do not show the labels, this is most applicable to chemvend jugs since now it's just like two dozen instances of 'jug' & you have you buy blind.
**Reproduction**

1. Purchase any ship with a chemvend (e.g. metastable)
2. Go to the chemvend and look at the options

**Additional context**

Fixed upstream 3 weeks ago in https://github.com/space-wizards/space-station-14/pull/29178

**Comment by ThatOneGoblin25** [comment]
Known issue. Will be fixed in the next upstream merge, #1679.
