### ISSUE TITLE
SyringeCognizine only draws

### ISSUE THREAD

**Issue by CautionDev** [new-frontiers-14/frontier-station-14#1688]
## Description

The cognizine syringe (SyringeCognizine) only draws when being used. Cannot be injected into containers or entities

**Reproduction**

Spawn the cognizine syringe entity on your local server and try to inject into an entity or container.

**Screenshots**

See attached video:
https://github.com/user-attachments/assets/80841ea0-39d2-472b-a292-5da6dab2a10e

**Additional context**

It's a drop in mail packages

**Comment by whatston3** [comment]
Parent's incorrect, should be SyringePrefilled.  Same with the opporozidone syringe.

Sorry about that.

**Comment by whatston3** [comment]
Fixed in #1691.
