### ISSUE TITLE
Station Records computer shows empty till someone latejoins

### ISSUE THREAD

**Issue by Katarn1933** [new-frontiers-14/frontier-station-14#1819]
## Description
Station records console is empty till someone latejoins. No fixes beyond latejoin seems to fix it

**Reproduction**
1) Buy a ship with station records console (ex. Sprinter) or access console on NFSD w\o NFSD present
2) Access console.
2.1) try typing something and searching in search bar
3) There will be no options for open slots

Same issue for NFSD. Till someone joins in you can't modify open slots

**Additional context**
While it might not be an issue if latejoin slots on ships are not quite intended, it is inconvenient and needs to look at to not cause issues down the line.

**Comment by whatston3** [comment]
Resolved with https://github.com/new-frontiers-14/frontier-station-14/pull/1954
