### ISSUE TITLE
Aggressive AI mobs cannot be damaged in pacifying zone, but can still attack

### ISSUE THREAD

**Issue by CautionDev** [new-frontiers-14/frontier-station-14#1873]
## Description

As far as I can tell from my testing, aggressive AI mobs cannot be damaged in pacifying zone, but can still attack. Sharkminnows definitley can.
**Reproduction**

**Screenshots**

**Additional context**

Maybe it can be reworked so that only those with less than 10 hrs of playtime can't damage in safezone. Provides protection against raiders while still leaving enough leniency to let people defend themselves from thefts, AI mobs, etc.

**Comment by arimah** [comment]
This issue is addressed by #1855, which I expect will be merged in not too long :)

**Comment by CautionDev** [comment]
Dope, didn't see that my bad
