### ISSUE TITLE
Vendors show NT bank info of last person to use them

### ISSUE THREAD

**Issue by PeccNeck** [new-frontiers-14/frontier-station-14#1927]
## Description
As the title says. This is purely cosmetic, and attempting to make purchases will update it to your account; as does exiting out and re-opening it, thus becoming the new last user.

**Reproduction**
- Have Player 1 open any vendor that accepts currency.
- Have Player 2 open that same vendor while the first player still has the UI open.
- Both players will see the balance of Player 2 in the UI.

**Screenshots**
![image](https://github.com/user-attachments/assets/c43f99ae-728a-403d-86b2-d6da8c276522)

**Additional context**
Cosmetic issue. This does not affect functionality.

**Comment by whatston3** [comment]
Should be resolved with last upstream merge, vendors pull bank balance from user's BankAccountComponent.
