### ISSUE TITLE
Moths have no special diet

### ISSUE THREAD

**Issue by PeccNeck** [new-frontiers-14/frontier-station-14#1928]
## Description
Moths cannot eat any form of cloth. Moths can also eat normal people food.

**Reproduction**
- Be Mothperson.
- Attempt to eat normal food, forgetting you're supposed to eat cloth- or cotton-based product.
- Successfully eat the normal food before remembering you're supposed to eat cloth- or cotton-based product.
- Attempt to eat cloth- or cotton-based product.
- You cannot eat cloth- or cotton-based product.
- Cloth- or cotton-based product.

**Screenshots**
![image](https://github.com/user-attachments/assets/34788d87-5f05-4ced-8f74-f36fcf8a6fba)

**Additional context**
This may be related to #1903 and #1839; unsure.

**Comment by whatston3** [comment]
Will be resolved with #1839.  Focus is currently on the upstream merge.

**Comment by whatston3** [comment]
Fixed with #2488.
