### ISSUE TITLE
NT Block Game does not work

### ISSUE THREAD

**Issue by PeccNeck** [new-frontiers-14/frontier-station-14#1930]
## Description
It just don't do. No errors logged by the client or by the server, it just doesn't seem to do... anything, at all. I know it used to, but that was also eight months ago.

**Reproduction**
- Find or make an NT block game arcade cabinet.
- Toggle UI, either through normal interaction or the right-click context menu.
- Coagulation, you're doned it.

**Screenshots**
![image](https://github.com/user-attachments/assets/d2ea684e-ccf1-4b31-a2a9-a9b4ad528910)
Space villain included on left for reference, unaffected.

**Additional context**
The Pause button does nothing as well; neither does pressing any keys.

**Comment by dvir001** [comment]
Should be fixed with the server upcoming update
