### ISSUE TITLE
SR jacket uses the old HOP winter jacket hood 

### ISSUE THREAD

**Issue by Leander-0** [new-frontiers-14/frontier-station-14#1942]
## Description

 Title, it needs the hood removed and SR needs his own winter jacket.

**Reproduction**

the the regular SR jacket and put it on.

**Screenshots**

![2024-09-05_09-14_1](https://github.com/user-attachments/assets/5bfca800-f9a2-4b9e-9164-abd66a3ae0e2)
![2024-09-05_09-14](https://github.com/user-attachments/assets/3ac417c6-7953-461f-a098-be09de1c423f)

**Comment by dvir001** [comment]
Already fixed in upstream update
