### ISSUE TITLE
Emergency Medipens...

### ISSUE THREAD

**Issue by Mamongaa** [new-frontiers-14/frontier-station-14#1955]
## Description
Any fights are prohibited on AF and you can't even throw things. But some find loopholes.... literally 4 emergency Medipens will kill anyone. I was often killed by raiders with this, often killed by Medipens during a spat and sometimes I didn't even have time to sell the shuttle...

**Reproduction**
Please, any fights are prohibited on AF, prohibit injecting any syringes and liquids into others. We have epinephrine in nanomed, a lot of medicine, which makes it possible to treat without hypo and emergency Medipens. Make it so that you can only inject yourself.

**Comment by whatston3** [comment]
Resolved with #2121, if this remains an issue, reopen as needed.
