### ISSUE TITLE
Military jumpsuits only show patterns on male characters

### ISSUE THREAD

**Issue by PeccNeck** [new-frontiers-14/frontier-station-14#1959]
## Description
Title. This appears in both the character editor and once spawned in, and for all species (except arachnid).

**Reproduction**

- In job loadouts, select any military jumpsuit
- Set your character's sex to Female
- The patterns are gone
- Spawn in (optional)
- The patterns are still gone

**Screenshots**
![image](https://github.com/user-attachments/assets/846a0c17-278d-4df4-8ba3-396c7e0edd4a)
![image](https://github.com/user-attachments/assets/bdccb020-6b02-45fb-ae26-ab88bfd80895)

**Additional context**
This applies to all job styles; with certain showing as their different "base" colors (e.g. Paramed's will be fully a dark teal, black jumpsuit will, ironically, be fully white).

**Comment by PeccNeck** [comment]
Bug persists a week later. Poked around in the relevant YML and sprites, couldn't find anything immediately obvious; if this is a C# issue, it's past the extent of my knowledge, or I could just be stupid and be overlooking something somewhere else in YML.

**Comment by whatston3** [comment]
Females tend to have displacement maps, and something about the way those work doesn't work well with the way the jumpsuit is layered.

**Comment by PeccNeck** [comment]
Finally got around to actually poking and looking around; turns out this bug also existed upstream, and was fixed in just two lines by https://github.com/space-wizards/space-station-14/pull/32553. Seems to be already incorporated in #2353, so hopefully we finally see this fixed soon.

Also, as it turns out, it affects other clothing items, too. The issue it mentions specifically calls out colorful costumes, but it even affects the basic colored jumpsuits as well (though it's quite a bit more subtle).

**Comment by PeccNeck** [comment]
Free at last.
