### ISSUE TITLE
Many Centcom items need contraband type change

### ISSUE THREAD

**Issue by dvir001** [new-frontiers-14/frontier-station-14#1993]
## Description
Centcom items parent from Syndicate.
This is mostly an issue that need to be fixed on upstream

Eg, Centcom pen using cybersun pen.

**Comment by whatston3** [comment]
Mostly resolved in the pending September merge, should do another pass.

**Comment by whatston3** [comment]
Going to mark this as resolved - can and will handle incorrect items individually.
