### ISSUE TITLE
Miasma planets might be killing carps in someway

### ISSUE THREAD

**Issue by dvir001** [new-frontiers-14/frontier-station-14#201]
## Description
Noticed all carps were dead when arrived, while they have no internals they somehow died. probably something related to miasma or something else with the air change. need to test

**Reproduction**
Lavaland tile set, hot temp, miasma in air.

**Additional context**
Need testing and change.

**Comment by Cheackraze** [comment]
might be the heat as well, worth testing, sad we cant have both, and immune to heat creatures wouldn't be great either with our reliance on laser weaponry for citizenry

**Comment by dvir001** [comment]
It was the heat

**Comment by sTiKyt** [comment]
> might be the heat as well, worth testing, sad we cant have both, and immune to heat creatures wouldn't be great either with our reliance on laser weaponry for citizenry

Any way to check if heat comes from a player's action or not? Maybe they could be immune to non-player heat?

**Comment by Cheackraze** [comment]
pretty sure this is no longer an issue since we got the neutered expeditions
