### ISSUE TITLE
Vox tank harness overrides outer clothing loadout choice, mask isn't worn by default

### ISSUE THREAD

**Issue by Samarai** [new-frontiers-14/frontier-station-14#2022]
## Description

When picking an outer clothing item in the loadout menu while playing as a vox, said item will not be given to you upon entering the round. It doesn't appear in your backpack, it's replaced with the tank harness even if it's capable of holding a full-sized air tank. 

Additionally, vox do not start with their selected mask equipped, but instead in their backpack, leading to some unavoidable toxin damage from breathing in oxygen depending on how fast a player can equip it and a nitrogen tank. 
**Reproduction**

1. Select vox.
2. Select any outer clothing item.
3. Spawn in.
4. Observe lack of outer clothing item, and the mask sitting in your backpack.

**Comment by whatston3** [comment]
Fixed the first half of this with https://github.com/new-frontiers-14/frontier-station-14/pull/2028.

Second half, wontfix.  Not worth keeping a second set of vox-specific masks that start equipped or finagling something up to fiddle with conditional loadout item placement.

Will resolve when the PR's closed.

**Comment by QRQ-2817** [comment]
> Fixed the first half of this with #2028.
> 
> Second half, wontfix. Not worth keeping a second set of vox-specific masks that start equipped or finagling something up to fiddle with conditional loadout item placement.
> 
> Will resolve when the PR's closed.

Frontier's atmos got fucked one round yesterday, resulting in a 75% oxygen composition. When spawning as a Vox, a single breath caused poison damage in the hundreds. In an instant, before you could even take your mask out and put it on, you were dead on the floor. 

Sure, this was an outlier case, but this situation wouldn't have happened at all if Vox simply spawned with their internals on.
