### ISSUE TITLE
aghosts cannot buckle anything

### ISSUE THREAD

**Issue by emrekmek** [new-frontiers-14/frontier-station-14#2049]
## Description
aghosts can no longer buckle anything to chairs since that update that made it so it takes time to buckle entities.

**Reproduction**
1. aghost
2. try to buckle living entity

**Comment by whatston3** [comment]
At the moment, it seems to be working as intended, I see no bugs.
Click+drag works as an aghost.
You can't buckle yourself, you're a ghost.
Using the right-click menu, dragging somebody brings up a buckle verb on right-click.

Seems fine on my side, closing issue for now, possibly resolved in last upstream merge.

**Comment by emrekmek** [comment]
Uploading buckle.mp4…

This is on the live server while admining.
