### ISSUE TITLE
Internal tanks automatically un-air their users if taken into the hand

### ISSUE THREAD

**Issue by githubuser4141** [new-frontiers-14/frontier-station-14#211]
## Description
A round ago I tried to beat a wall with the oxygen tank I had on my suit in a hazardsuit atmosphere. Instead of my character taking it into his hand to smack the wall, my character instead removed it from his internals leading to an instant, poorly explained death.

**Reproduction**
Get an internals tank, equip it on a suit and turn it on.
Next, grab it in your hands and try to click something with it. Without explanation or warning, your character will instantly turn it off. This is pretty poor gameplay design, it's unintuitive because in real life I'd be able to hold it in my hand with the pipe going to my mask and bang things with it, instead of automatically turning it off in a risky situation. There are videos and images of people holding 02 tanks and using them at the same time on the internet.

**Additional context**
SS14 is advertised to be a newbie-friendly, more user-friendly, better quality of life game then SS13, so probably shouldn't feature odd designs where your character decides to kill themselves like this.

**Comment by dvir001** [comment]
Hey, this is a upstream issue, not frontier.
Please open this on the SS14 github.

**Comment by githubuser4141** [comment]
> Hey, this is a upstream issue, not frontier. Please open this on the SS14 github.

gotcha
