### ISSUE TITLE
Some items are not listed correctly on vendor (Nanomed)

### ISSUE THREAD

**Issue by ZombieChibiXD** [new-frontiers-14/frontier-station-14#2116]
## Description
Some items (implanters at the moment) doesn't correctly show what they're supposed to be

**Reproduction**
Clone to HEAD on github, attempt to open a nanomed plus vender, see implanters being not clear.

**Screenshots**
![image](https://github.com/user-attachments/assets/d9342018-555b-4a2d-9507-8de5c93513a3)

**Additional context**
The same bug as chem not correctly showing on chemvend, but this time it's something to do with frontier only since Upstream changed how the UI looks, so it might be an issue there.

**Comment by whatston3** [comment]
Resolved with #2118.
