### ISSUE TITLE
Ship is entirely black, unable to do any interaction

### ISSUE THREAD

**Issue by githubuser4141** [new-frontiers-14/frontier-station-14#212]
## Description
After my internet cut out when piloting a ship, I came back to see a completely dark ship.

As you can see, my flashlight is on, powered, but is not producing any light. I am completely unable to do any interaction such as selling my ship or interacting with an ATM before the round ends. This causes a softlock which requires an admin to help (as 90% of the crew seem to be in OOC groups and will likely not help you)

**Reproduction**
Not 100% sure what caused the issue, but this is how I experienced it:
Pilot a ship, in my case, fly it away from the main hub.
Disconnect your internet until the server brings you to the "lost connection screen".
Reconnect, and try to reconnect.

**Screenshots**
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/61243846/d993816c-d5cb-4c19-80b6-3e43ddafb268)

If you squint, you should see the trusses and vague black shape of the ship

**Additional context**
Not sure if this is a SS14 issue or a Frontier one

UPDATE: This continued to happen on a fresh round, and was resolved when I manually exited and re-connected to the server.

**Comment by dvir001** [comment]
Game issue, and reported already on main SS14

**Comment by Zaknhrae** [comment]
The only way to solve this issue for now is restarting the launcher. If you just disconnect and reconnect the server without closing and opening the launcher again it will persist,

**Comment by DebugOk** [comment]
> The only way to solve this issue for now is restarting the launcher. If you just disconnect and reconnect the server without closing and opening the launcher again it will persist,

The game*

The launcher has nothing to do with this bug, a fix for it is already present in the engine

**Comment by Cheackraze** [comment]
> > The only way to solve this issue for now is restarting the launcher. If you just disconnect and reconnect the server without closing and opening the launcher again it will persist,
> 
> The game*
> 
> The launcher has nothing to do with this bug, a fix for it is already present in the engine

For anyone curious, I'm planning to merge upstream and get this fix as soon as I hear borgs are stable and less buggy than not
