### ISSUE TITLE
Pirate bounty exchange doesn't work when proper items are placed

### ISSUE THREAD

**Issue by Qulibly** [new-frontiers-14/frontier-station-14#2132]
## Description

Even though items are in proper crates or accepted, it doesnt seem to detect them at the exchange.

**Reproduction**

Accept bounty
Fill with requested item
Try to appraise/reclaim

**Screenshots**

![obraz](https://github.com/user-attachments/assets/806b0b6b-fb57-483b-9eb1-05307c63c73a)

**Additional context**

I have lately played Pirate abit. and once came back to Cove, weren able to turn the right loot into doubloons. It happened end of round. but could have caused issues.

**Comment by whatston3** [comment]
Plunder exchange isn't the bounty redemption computer.  Working as intended, use the console to the left.

**Comment by whatston3** [comment]
The only thing at the moment that can be redeemed through the pirate bounty console is individual contraband crates, which you'll occasionally get a ping about if there are active smugglers.

Ideally there'd be more individual items to sell.  There's an unmapped pirate equivalent of the contraband appraisal gun that'll tell you something's value in doubloons.  It'd be useful for this console, as it's for selling loose items in the same way that the NFSD has contraband turn-in.
