### ISSUE TITLE
Bluespace NT Vault (both sizes) fail to spawn due to missing BookSecretDocuments prototype

### ISSUE THREAD

**Issue by GreyMario** [new-frontiers-14/frontier-station-14#2147]
## Description
The NT Vault bluespace events fail to spawn the appropriate grid when triggered. This appears to be caused by an upstream merge killing off the HoS' security orders, `BookSecretDocuments`.

**Reproduction**
Attempt to manually load the grids `/Maps/_NF/Bluespace/vault.yml` or `/Maps/_NF/Bluespace/vaultsmall.yml`. Receive error in server console.
```
[INFO] loader: Loading Map: /Maps/_NF/Bluespace/vaultsmall.yml
[ERRO] loader: Missing prototype for map: BookSecretDocuments
[ERRO] loader: Found missing prototypes in map file. Missing prototypes have been dumped to logs.
```

`/Maps/_NF/Bluespace/datacarrier.yml` is also affected by a missing `PlushieSlips` prototype.

**Comment by dvir001** [comment]
Removed data carrier on https://github.com/new-frontiers-14/frontier-station-14/pull/2148
Honestly this event is too much of a mess to refix since it has other issues also.
