### ISSUE TITLE
Shovels instashovels when canceling action

### ISSUE THREAD

**Issue by Myzumi** [new-frontiers-14/frontier-station-14#2167]
## Description

When trying to shovel dirt with a shovel and trying to cancel it by moving or any other way of canceling the action bar, instantly removes the targeted dirt plate.
**Reproduction**

- Floor in Dirt
- Get a shovel
- Try to shovel dirt
- Try to cancel the interaction/action by moving or something other
- Get dirt but you didn't wanted to shovel that
**Screenshots**

**Additional context**

**Comment by PeccNeck** [comment]
Solved with #2188
