### ISSUE TITLE
Building ships from non-bought grid disables cruise modes

### ISSUE THREAD

**Issue by AJimmyU** [new-frontiers-14/frontier-station-14#2185]
## Description

Building a new ship by building a new grid does not allow the new ship to use cruise/park/drive modes.

**Reproduction**

1. Place down a new grid with rods
2. Power a shuttle console
3. Notice no option for drive modes

**Screenshots**

**Additional context**

**Comment by dvir001** [comment]
Intended, can this be abused in someway?

**Comment by Cheackraze** [comment]
> Intended, can this be abused in someway?

yes, by making a bunch of little grids and putting them in 'park' to clutter up space is why we did it. Some form of a device that registers a grid as a proper 'ship' is whats needed to help that.

For now this is intentional.
