### ISSUE TITLE
Syndicate outpost vendors getting destroyed in a rush

### ISSUE THREAD

**Issue by AJimmyU** [new-frontiers-14/frontier-station-14#2222]
## Description

Syndicate outpost vendors keep getting rushed and destroyed by (I'm assuming) NFSD players, removing a fun game mechanic permanently from the round. These vendors should be made indestructible so people can restore the syndicate outpost and still interact with it.

Especially lame since you have to play from start of round to even have a chance to beat these rushes.

**Reproduction**

Play any round, wait an hour or two, watch as someone destroys all syndi vendors preventing anyone from ever interacting with the outpost.

**Screenshots**

**Additional context**

I'm not sure how this happens practically every round, but it's stupid that players can deny such a feature for everyone for a whole round by just powergaming hard enough.

**Comment by dvir001** [comment]
Vending machine should be destroyable as letting it stay makes it impossible for NFSD to neutralize the outpost.

Also, there been a change in the code to the POI and to vending that is still missing on the server that fixes the general issues.

https://github.com/new-frontiers-14/frontier-station-14/pull/2146
