### ISSUE TITLE
PTK-800 destroys itself when mining / disappearing projectiles

### ISSUE THREAD

**Issue by AJimmyU** [new-frontiers-14/frontier-station-14#2223]
## Description

1. PTK-800 when used as a mining weapon on a shuttle will destroy itself after few shots due to asteroid wall reflections, mandating time consuming relinking of signals to allow repeat use.

2. PTK-800 projectiles do not seem to affect asteroids that weren't visually visited by a player. This might be an observation error on my part, but unless I have seen the asteroid on my screen (not just on ship radar), the PTK-800 projectiles do not seem to actually hit the asteroid no matter how long I shoot at it.

**Reproduction**

1. Mine asteroid with PTK-800 shuttle weapon
2. Watch it destroy itself due to reflection

**Screenshots**

**Additional context**

I have a feeling that this reflection was intentionally introduced to make the PTK-800 useless for actually mining asteroids and to make hand mining for some reason preferable.

If it's intended to be useless for mining, it shouldn't be for sale as it's just a trap for new players to waste credits on.

**Comment by dvir001** [comment]
![image](https://github.com/user-attachments/assets/5a4887c4-93e4-4368-94a6-c8ba60f28b64)

Fix them with welding
Dont spam them, use them in a smart setup.

**Comment by dvir001** [comment]
The picture showing why the walls reflect now.

**Comment by dvir001** [comment]
Not in the game right now to picture it.

but in general, you might want to have small amount (3~) and move around an asteroid while hitting it from some range, but not over 120~.

Or have a crew that is working on maintaining them if you still want to use alot.

**Comment by dvir001** [comment]
1. Russian Frontier
2. Orebox collect, or work in a team.
3. Massive PTK Setup before this change didnt need more then one-man solo on a RP server.
4. What setup time? flatpack wires and linking?

**Comment by burrrkeye** [comment]
You ideally want a 3 man crew. 
Captain, maintainer and hauler. 
You want to find the range at which the shots are not able to reach your turrets upon reflection. Use the circles on your radar. Ask your crew if any shots reflected. 
Rock type asteroids (orange outline on radar) spawn no walls that can reflect. Target these asteroids. If you are not targeting these asteroids, find the range at which reflected shots die out before reaching the turrets
Have fun mining without any death risk
