### ISSUE TITLE
Loadout Implanters are not labled correctly

### ISSUE THREAD

**Issue by Havaren** [new-frontiers-14/frontier-station-14#2250]
## Description
Load out Implanter selection no longer lists what the implanter is, they are all just called "implanter"

**Reproduction**
Go to Customize, select mect, contractor or any job, go to implanters.

**Screenshots**
https://i.imgur.com/L9cRBS0.png
https://imgur.com/hNHNO7X

**Additional context**

**Comment by ErhardSteinhauer** [comment]
Fixed here: https://github.com/new-frontiers-14/frontier-station-14/pull/2235
