### ISSUE TITLE
Panic Bunker connection message does not show the hours property.

### ISSUE THREAD

**Issue by worldofrice** [new-frontiers-14/frontier-station-14#2299]
## Description

When connecting to the server when the server is busy and you lack the playtime requirement, the connection is denied and the following connection message is presented: 

> This server is in panic bunker mode, often enabled as a precaution against raids. New connections by accounts not meeting certain requirements are temporarily not accepted. Try again later. Reason: "Your overall playtime on the server must be greater than {$hours} hours" 

Problem being, the text formatting seems to not be working for the 'hours' property. See attached screenshot below.

**Reproduction**

This error occurred joining the Frontier Hypatia [US 1] server while not having enough playtime to join. 

**Screenshots**

![image](https://github.com/user-attachments/assets/153e9cf5-e771-4109-b060-faa52ece3c21)

**Comment by whatston3** [comment]
Give me a bit, I'll fix this.

**Comment by whatston3** [comment]
Fixed in #2300.
