### ISSUE TITLE
Visual issue with ghost mode when returing to body

### ISSUE THREAD

**Issue by Of-paterns-and-lines** [new-frontiers-14/frontier-station-14#2395]
## Description

Well i was on an non-id vessel (bluespace event) with the clowns ,i died while fighting a tough NPC ,then looked around a bit,when i tried to return to the body the game would visually freeze on the game world,but the chat logs and all buttons/options work normally. It was not a lag issue of what im aware. 

**Reproduction**

1.Be dead on an unidentified vessel.
2.Leave the body and tp to someone else or look around.
3.Timer hits and it despawns  the vessel
4. Attempt to return to the body. 

**Screenshots**

-Not available-  (i did not know if it was a bug or not when it was happening)

**Additional context**

The screen of the game world would freeze but the game was working normally and every player in the game was interacting normally and so were comms. mostly visual ghost-to-body issue.

**Comment by PeccNeck** [comment]
Sentenced to the shadow realm.

**Comment by whatston3** [comment]
Might've been sent to nullspace - this was changed with #2337 (different detach function) - your body should stick around after the event.  Couldn't reproduce this one locally (body does stick around on the default map), I'm assuming it's fixed.  If not, do reopen this.
