### ISSUE TITLE
FUC loophole with contraband blueprints

### ISSUE THREAD

**Issue by Aineias1** [new-frontiers-14/frontier-station-14#2458]
## Description

You can print shitload of C3 contraband that can be sold for 1 or 2 FUCs depending on what you print
**Reproduction**

1) Get a holopickaxe blueprint(easiest) and insert it in any fabricator
2) Mine/Find on expeds lots of mats and print these, it's honestly too cheap for the ammount of fucs
3)Profit
**Screenshots**

![image](https://github.com/user-attachments/assets/d43121ba-edcd-495e-bcf0-2a118be174d2)
![image](https://github.com/user-attachments/assets/57521327-2865-48fe-9bdd-1612e36bb808)
![image](https://github.com/user-attachments/assets/9dcc5994-f60c-417b-904b-c5a9f2217ea3)

**Additional context**

I made all that, going on minor danger expeditions alone

**Comment by dvir001** [comment]
If you actually see someone doing this please ahelp, I hope you did report about the people in the picture.

Thanks for the bug report.

**Comment by Aineias1** [comment]
I was the one who did that

**Comment by whatston3** [comment]
A more maintainable long-term fix for this might be to have a policy of making all contraband definitions have 0 value (so we won't need so many), and anything with actual value must be explicitly defined in that entity's definition.

If there were only a handful of sources of FUCs (bounties for enemies in "please clear this" bluespace events, thresholded values/bookkeeping for specific prizes on the "please guard this" bluespace events, anti-smuggling action, anti-smuggling detective work), this'd be less prone to need whack-a-mole fixes.

**Comment by Aineias1** [comment]
Maybe just tag contra items that were printed so they don't cost anything
