### ISSUE TITLE
Delerict plasma of doom

### ISSUE THREAD

**Issue by Of-paterns-and-lines** [new-frontiers-14/frontier-station-14#2480]
## Description

Plasma fuel found on derelicts breaks game UI and interactions, whilst was holding it the UI of bag n such broke,and some UI buttons like F1 (for ahelp) did not work when pressing. It might become a large issue in some scenarios or get people killed in some circumstances.

**Reproduction**

-find derelict 

-Find the plasma
(slightly shinier,can also be inside gens,it shows 0 fuel left usually,might be infinite in em. tested on my own gen and it shows properly)

-hold in hand .

-interact in many ways.

**Screenshots**

![1482520_271](https://github.com/user-attachments/assets/99b302c3-1f0c-4b9c-87b4-d8cd31c1d683)

**Additional context**

Also ahelped to make sure its not just sth wrong with the game world,took a look and determined its the plasma found on the derelict.

**Comment by dvir001** [comment]
Funny its actually an issue with a ship you can just buy from the scrap shipyard called "point" but no one ever buy it.
Anyway, fixed in a moment in a new PR.
