### ISSUE TITLE
Air tanks in EVA Vendor cause suffocation due to high default pressure release

### ISSUE THREAD

**Issue by GrandKadoer** [new-frontiers-14/frontier-station-14#250]
The air tank purchased from the eva vendor comes preset to 101 kpa compared to an O2 tanks default 21 kpa. This results in inexperiened players taking out a prospector and suffocating five times as quickly before they can find an air canister to refill at.
In the interest of gameplay, I think these air tanks should be replaced with O2 tanks in the vendor.

**Comment by Cheackraze** [comment]
Air tanks (the white ones) have standard atmos mix 80/20 nitrogen/oxygen, and are usable by both slimes and humans etc.  101.35 kpa is the correct pressure for these tanks otherwise you will suffocate from not enough air

**Comment by GrandKadoer** [comment]
These air tanks have 0 pressure when they're purchased from the vendor, meaning someone fills them with O2, assumes they're good, and suffocate 5x as fast. There is no feedback ingame to make you realize that you're consuming five times the normal rate of oxygen.

**Comment by Cheackraze** [comment]
> These air tanks have 0 pressure when they're purchased from the vendor, meaning someone fills them with O2, assumes they're good, and suffocate 5x as fast. There is no feedback ingame to make you realize that you're consuming five times the normal rate of oxygen.

changing the prototype to be lower pressure will cause filled ones to suffocate people who don't realize that they need to manually increase the pressure from 20.1 to 101 on any filled air tank. The solution is to make them come filled, and IMO the real 'problem' could actually be a really good atmos teaching tool so long as we adhere to a proper visual language, blue=oxy, red=nitro, white=mixed air

**Comment by GrandKadoer** [comment]
Yeah I wouldn't mind that either. Thanks for the discussion!
