### ISSUE TITLE
Ore processor can process raw diamond only in 10 units

### ISSUE THREAD

**Issue by Katarn1933** [new-frontiers-14/frontier-station-14#2516]
## Description
When trying to print processed diamond from raw diamond through ore processor it won't print if you insert less than 10 units of raw diamond.
It WILL print 10 processed diamonds, but description says 'need 1 unit'
**Reproduction**
Spawn ore processor, spawn stack of raw diamond ore. insert less than 10 units, try to print. insert 10 units - it will print 10 units of processed diamonds.

**Comment by dvir001** [comment]
Did you change the number under to 1?

**Comment by whatston3** [comment]
Not an issue.
![image](https://github.com/user-attachments/assets/5a3e366c-77e0-4d89-b9e4-2833ae47564d)

**Comment by Katarn1933** [comment]
yeah, feel stupid now
but this is first time I saw it using Amount 10
usually it uses Amount 1 by default

**Comment by whatston3** [comment]
Again, no: https://github.com/space-wizards/space-station-14/pull/31074/files#diff-3510e12224a50e5ea9477d838ec956c93301b0ad893401037206752332fde6daR1171

This is the change that introduced that amount - this is upstream behaviour.

**Comment by dvir001** [comment]
To be honest we should probably have it set to 1 on start, not 10
