### ISSUE TITLE
Ships NT prefix

### ISSUE THREAD

**Issue by dvir001** [new-frontiers-14/frontier-station-14#252]
## Description
We should probably start omitting all the "NT" prefix from all ships names to be less annoying on the radar.

This will require removing the {0} added to ships names, with no need to change the code here:

https://github.com/new-frontiers-14/frontier-station-14/blob/8674a1ecd2c807aecf569a79cd28d6c4d5757ffe/Content.Server/Maps/NameGenerators/NanotrasenNameGenerator.cs#L7

**Comment by TsjipTsjip** [comment]
Issue seems to be resolved. Can you confirm?

**Comment by dvir001** [comment]
> Issue seems to be resolved. Can you confirm?

I found 2 ships that still had wrong names format but I made a fix in the large ship moving pr of #905
