### ISSUE TITLE
Survival boxes may drop on spawn

### ISSUE THREAD

**Issue by Radezolid** [new-frontiers-14/frontier-station-14#2522]
## Description
Title.

**Reproduction**
1. Select from loadout several keys, insurance implant and spawn with a satchel.
2. Notice the survival kit on the floor once you spawn.

**Screenshots**
![image](https://github.com/user-attachments/assets/bbe4cded-00cb-4ec7-a627-c3be25398e8d)

**Additional context**

None.

**Comment by dvir001** [comment]
Aware, thanks for the report as it will help keep it tracked,

The true fix will be moving the keys into headset on spawn, implants to body and pda programs to PDA as to allow more inventory space.

**Comment by whatston3** [comment]
Try bringing less stuff with you next time. :)

**Comment by Radezolid** [comment]
:)
