### ISSUE TITLE
Fuel-Grade Uranium/Plasma becomes normal fuel after deconstructing

### ISSUE THREAD

**Issue by blackknight954** [new-frontiers-14/frontier-station-14#2554]
## Description
When inserting plasma into a PACMAN or SUPERPACMAN,  Screwdriver and crowbarring it turns the fuel into regular uranium/plasma instead of fuel grade. 
**Reproduction**
Make a PACMAN

Spawn Plasma (fuel grade or otherwise) and insert it

Deconstruct the generator

Get actual Plasma

**Screenshots**
![image](https://github.com/user-attachments/assets/4c04b8f4-39d9-4ad3-94a2-e5fc23f0331c)

**Additional context**
Additionally, hitting eject on the UI turns it into fuel grade Uranium/plasma, regardless of it you bought fuel grade items or mined it

**Comment by dvir001** [comment]
Thanks for the report

**Comment by whatston3** [comment]
Easy, crappy fix: set MaterialStorageComponent.DropOnDeconstruct to false for Frontier portable generators that aren't the JRPACMAN.
Trickier but better fix: convert the material when inserted to a fuel-grade material version, then spawn this material when deconstructing (automatic - material will be linked to a prototype).
