### ISSUE TITLE
NFSD Outpost cannot use Selling Cargo Pad

### ISSUE THREAD

**Issue by Myzumi** [new-frontiers-14/frontier-station-14#2555]
## Description

The NFSD Outpost cannot use the NFSD cargo Console, this might be due to the wrong cargo pallets?
Atleast stuff like Steel, Glass etc that you can sell at the TO/Mall cannot be sold here
**Reproduction**

- Go to NFSD
- Try  selling something
- No Workie
**Screenshots**

**Additional context**

**Comment by whatston3** [comment]
Need to be swapped out for the cargo sell pallet, the cargo pallet's had its buy/sell ability removed.
