### ISSUE TITLE
Science servers connecting to other servers.

### ISSUE THREAD

**Issue by Enon00** [new-frontiers-14/frontier-station-14#303]
<I've seen that with some research consols that once they've been created they do not connect to the server thats on the ship but, instead connect to the oldest server (i.e if science ship 4 creates an tech disk machine, it will connect to science ship 1 and be able to take all their research).>

**Reproduction**
<have two servers on seperate ships, (two sparrows as an example and have) and have on build any machine able to connect to a server. Instead of connecting to the server that its apart of (Sparrow 2) it will instead go to the oldest server (Sparrow 1)>

**Comment by dvir001** [comment]
I have seem this isuue live, this is only when you build a server (Map init issue)

**Comment by dvir001** [comment]
https://github.com/new-frontiers-14/frontier-station-14/pull/456

**Comment by Cheackraze** [comment]
this specific issue has been resolved but servers still act a bit wonky, but we should open a new issue with the new problem so closing this one as resolved
