### ISSUE TITLE
FTL Into rocks

### ISSUE THREAD

**Issue by dvir001** [new-frontiers-14/frontier-station-14#326]
## Description
FTL Missing a lookup if its putting you back into an empty space or a grid

**Reproduction**
FTL Back, get stuck in some other grid

**Screenshots**
Dont have one.

**Additional context**
FTL Need to scan for empty area.

**Comment by Cheackraze** [comment]
upstream issue sadly

**Comment by dvir001** [comment]
> upstream issue sadly

Do we want to make an attempt to fix it or just wait it out assuming someone care?

**Comment by dvir001** [comment]
Seems like upstream update fixed this, mostly.
