### ISSUE TITLE
SV Tide - Grav Generator

### ISSUE THREAD

**Issue by hord-brayden** [new-frontiers-14/frontier-station-14#407]
## Description

Purchasing a new Tide ship, it's very clear there's no grav genny included in the purchase. However what's not-clear, and probably unintended, is if you do come across a grav generator from another source, it still doesn't work inside the tide.

**Reproduction**

1. Purchase Tide
2. Acquire Grav gen, install and power up
3. Experience the weightlessness of expectations being unmet

**Screenshots**

**Additional context**

**Comment by Cheackraze** [comment]
Make sure to report this upstream

**Comment by hord-brayden** [comment]
> Make sure to report this upstream

That's what my thought was, but I can't replicate upstream. I'm curious if it's something to do with this fork? I've done this with other shuttles as well and they treat it just fine. I'm curious if it's intrinsic to this shuttle or the fork, or? For example - on Wizden you can slap a grav gen on an escape pod, and it'll work as intended the last time I checked.

**Comment by Cheackraze** [comment]
There's nothing different here about gravity, I know of no reason why it would be frontier specific, but it may be something specific to that shuttle.

**Comment by hord-brayden** [comment]
> There's nothing different here about gravity, I know of no reason why it would be frontier specific, but it may be something specific to that shuttle.

Gotcha, okay I'll do some more investigation and report back when I have some more answers. Thanks @Cheackraze

**Comment by Carolyn3114** [comment]
> There's nothing different here about gravity, I know of no reason why it would be frontier specific, but it may be something specific to that shuttle.

it could be an issue with grids spawning with zero gravity, it also doesn't work if you put a gravity generator on an asteroid or wreck

**Comment by Cheackraze** [comment]
> > There's nothing different here about gravity, I know of no reason why it would be frontier specific, but it may be something specific to that shuttle.
> 
> it could be an issue with grids spawning with zero gravity, it also doesn't work if you put a gravity generator on an asteroid or wreck

Hrm... I did not know this either.  Maybe it is something broken with the grids then, if it spawns with no gravity it can never have it? Very strange behavior, but also leads me to believe it's an upstream issue again

**Comment by PeccNeck** [comment]
I can't seem to replicate this, at least not anymore. Both on the grav-less SV ships and on space debris (including asteroids) spawning or building a mini gravity generator does seem to generate gravity (provided you give it the time and power to charge, of course).

If it was an upstream issue, it seems to be fixed now, or my replication method is wrong.

![image](https://github.com/new-frontiers-14/frontier-station-14/assets/74548962/85f3605f-b308-4c41-9aa1-957ffbf26aad)

**Comment by Cheackraze** [comment]
> I can't seem to replicate this, at least not anymore. Both on the grav-less SV ships and on space debris (including asteroids) spawning or building a mini gravity generator does seem to generate gravity (provided you give it the time and power to charge, of course).
> 
> If it was an upstream issue, it seems to be fixed now, or my replication method is wrong.
> 
> ![image](https://user-images.githubusercontent.com/74548962/278273170-85f3605f-b308-4c41-9aa1-957ffbf26aad.png)

glad to hear its resolved, the nature of this one was hard to define and nail down.
