### ISSUE TITLE
It’s not about a quick fix. We are supposed to balance things. They already take forever to actually lift off, and they allow for more creative gameplay. A simple but effective fix would be that damaging the crate simply removes the Fulton, and they can’t be put on cargo crates. Then just make it so they take double the extraction time in space, so it’s litteraly just easier to walk. Fultons do highlight a problem though, and that is the absaloute pain that is maneuvering cargo crates. Maybe we need a sort of crate trolly item?

### ISSUE THREAD

**Issue by Cheackraze** [new-frontiers-14/frontier-station-14#408]
It’s not about a quick fix. We are supposed to balance things. They already take forever to actually lift off, and they allow for more creative gameplay. A simple but effective fix would be that damaging the crate simply removes the Fulton, and they can’t be put on cargo crates. Then just make it so they take double the extraction time in space, so it’s litteraly just easier to walk. Fultons do highlight a problem though, and that is the absaloute pain that is maneuvering cargo crates. Maybe we need a sort of crate trolly item?

_Originally posted by @Carmell0 in https://github.com/new-frontiers-14/frontier-station-14/issues/402#issuecomment-1756113679_
            
We already have something in the game that fultons are superseding, the Ripley, and in a game that's core gameplay loop is about traveling in vehicles, instant teleportation has 0 place fundamentally.

**Comment by Carmell0** [comment]
I agree, they need balancing, but shouldn’t be outright deleted. Maybe your ship needs to be docked with whatever is sending the Fultons for it to work?
