### ISSUE TITLE
Check Merge Conflicts failed

### ISSUE THREAD

**Issue by PeccNeck** [new-frontiers-14/frontier-station-14#475]
## Description
The big red X that plagues every pull request and commit, caused by just one action meant to detect merge conflicts apparently not having access to a resource. I'm not all too familiar with GitHub Actions but it would be nice to turn that red to green when there isn't actually an issue.

**Reproduction**
Make a pull request.

**Screenshots**
Not necessary, [see for yourself.](https://github.com/new-frontiers-14/frontier-station-14/actions/workflows/conflict-labeler.yml)

**Additional context**
My best guess after taking a brief look is just that it's trying to apply a label that doesn't exist. In my completely uneducated theory, the solution should be as simple as a maintainer adding a label named `Merge Conflict` (presumably case-sensitive). If that doesn't work, I say we erase or disable the action entirely.

Low-priority issue, if you couldn't tell.

**Comment by PeccNeck** [comment]
I love basic logical deduction. Cause and solution confirmed; it's the missing label. At least in theory. In practice, I forgot to define a control group in my own repo, but good enough.

**Comment by Cheackraze** [comment]
was also due to wrong perms but fixed now finally
