### ISSUE TITLE
Add a ship owner note on every ship / code owner.

### ISSUE THREAD

**Issue by dvir001** [new-frontiers-14/frontier-station-14#546]
## Description
Right now there isn't a fast way to find a ship maker other then looking into PR or trying to find them based on username in discord
There need to be notes on every ship to allow fast feedback on them for fixing issues.
Ship maintainer, + discord ID and username

**Comment by YumiGumi** [comment]
I have update ideas for my ship, i'll add a paper with my stuff signed and what not next PR for it.

**Comment by whatston3** [comment]
Going to mark this as complete - the majority of ships and POIs have their maintainer info in their vessel/POI prototype.  Certain ones that don't (e.g. Empress) should be fixed ad hoc and brought up to standards.
