### ISSUE TITLE
Join Game Bug

### ISSUE THREAD

**Issue by Ablankmann** [new-frontiers-14/frontier-station-14#559]
## Description

If you have the join menu open when a shuttle is added or otherwise edited, the UI lights them up as if you can play roles you shouldn't be able to without a whitelist or the role's time.

**Reproduction**

- Have game menu open with Frontier Station on the selection
- Have a player-controlled ship spawn that has roles
- Roles you don't have time for/a Whitelist for on Frontier, now light up as if you could already play them, as long as a slot is open and the Menu is open
- Closing the menu will return these to being greyed out as before

**Screenshots**

![image](https://github.com/new-frontiers-14/frontier-station-14/assets/103340990/4965fc78-9626-4c50-8ace-77ea304f44dc)

**Additional context**

Accidentally found this while tweaking my settings while having the menu open, unsure if the menu is just a visual thing or if this can be abused to get roles in Security or otherwise illegitimately

**Comment by whatston3** [comment]
Fixed with #1716.
