### ISSUE TITLE
RD servers are not working on point of interest

### ISSUE THREAD

**Issue by RealIHaveANameOfficial** [new-frontiers-14/frontier-station-14#596]
## Description

R&D servers cannot be selected for machines that are on points of interest
**Reproduction**

-Go to point of interest (e.g. anomalous lab)
-Find any machine that connects to server
-Go to Server list
-See that there are no servers
This happens even after rebuilding all devices involved in this, including the RD server itself
You can drag the RD server onto a shuttle and it will then become able to be connected to. I think this issue is related to the bandaid fix for default RD server sharing, but I haven't looked yet.
**Screenshots**

**Additional context**

This really needs fixed because if we're going to make PoI's unable to be looted as we seem to intend to, then if we make machines unanchorable, people are going to disassemble them and take the boards, though maybe we can make them uncrowbarable? I dunno. Needs addressed.

overall I think this is a bigger issue with RD server fuckery but for right now it makes it impossible to set up a lab on a PoI which is especially problematic for the new anomalous lab.

**Comment by dvir001** [comment]
This was fixed.
