### ISSUE TITLE
Phoenix Shuttle spawns with unwired solars

### ISSUE THREAD

**Issue by DangerRevoltion** [new-frontiers-14/frontier-station-14#646]
## Description

The Solar panels to the north-east, to the right of the shuttle console (assuming the docking area is south) spawn naturally unwired.
**Reproduction**

1. Buy shuttle
2. Board shuttle
3. EVA outside through the salvage door
4. Head to the exterior of the cockpit, on your right
5. Pass the solar tracker
6. Look at the unwired solar panels
**Screenshots**

I'll update later with a screenshot when I can get on
**Additional context**

This is inconvenient as it means you have to go buy a HV crate or you have to get steel to make HV cables.

**Comment by RealIHaveANameOfficial** [comment]
fixed in https://github.com/new-frontiers-14/frontier-station-14/pull/652
