### ISSUE TITLE
Not super important but slight spelling errors in Medical Insurance Document/Contract

### ISSUE THREAD

**Issue by MrKestryl** [new-frontiers-14/frontier-station-14#672]
## Description
A few of misspellings in the medical insurance contract documents, I found them in the Pioneer ship (not sure if in other places on the station or other ships)
"frovider" should be "provider"
"attem" should be "attempt"
"were" should be "we're"
**Reproduction**
Open insurance box, take and open document.

**Screenshots**
![369be2a112463dfbfc2a1cf822b5907f](https://github.com/new-frontiers-14/frontier-station-14/assets/112631534/02b1f877-193e-4805-8897-02d03d983259)

**Comment by Wolfking6116** [comment]
A baseline medical insurance template is still a bit of a necessity for those who are just starting off or not creative enough to create their own pricing and templates from scratch.

**Comment by dvir001** [comment]
The doc was removed
