### ISSUE TITLE
Bazaar vessel purchase bug 

### ISSUE THREAD

**Issue by Enon00** [new-frontiers-14/frontier-station-14#707]
## Description
When purchasing the Bazaar from the shipyard console, the machine will make a noise saying that you dont have enough money however will take money away from the player. There's no clear indication that the vessel is not going to appear apart from their being no ship ID on your personal ID leading to players not understanding or being confused that the vessel will not ever appear.

**Reproduction**
put in your ID, purchase the Bazaar and watch the money vanish with no ship appearing.

**Comment by mnemosynium** [comment]
This is due to the recent change to mercenary gear:

```
[INFO] loader: Loading Map: /Maps/Shuttles/bazaar.yml
[ERRO] loader: Missing prototype for map: ClothingBackpackMerc
[ERRO] loader: Found missing prototypes in map file. Missing prototypes have been dumped to logs.
```

**Comment by YumiGumi** [comment]
Understood, will fix tomorrow, seems the merc update broke some stuff aboard the vessel
