### ISSUE TITLE
Mail Loot Table needs rewriting

### ISSUE THREAD

**Issue by Cheackraze** [new-frontiers-14/frontier-station-14#766]
## Description

its basically the same as what was from nyano around 1 year ago.  At the moment, there are different loot tables for individual jobs, but these are tied to round-start or late-join job prototypes, and doesnt translate well to frontier, where 95% of players are passenger upgraded to captains.

Ideally, we would move it all to a big giant generic loot pool for all jobs. Im willing to still have SR/Sheriff get unique mails, because those roles actually get placed into their job prototype roles via the game code, whereas everyone else is technically a passenger and it only pulls from the passenger list.

Thats besides the point that its just an old loot table and is pretty boring anyway. We should jazz it up a bit, put some cash stacks of like 5k in the loot pool etc. Make them more exciting to open than just some snacks or a bad joke.

**Comment by dvir001** [comment]
SR Pipe bomb moment

All of it except sec jobs/Frontier command need to be shared pool.

**Comment by FoxxoTrystan** [comment]
Active bomb on unwarp, hmmmm nice.
