### ISSUE TITLE
Large Lizards are way stronger than Onis

### ISSUE THREAD

**Issue by dflttxt** [new-frontiers-14/frontier-station-14#770]
After some playful shoving contests, I realized that Onis are overshadowed by large Lizard people in alot of ways when compared to each other.

Onis whole identity is barely any aim and pure muscles, but its hugely undermined when there's a mutation of a species that overpowers them during close quarter combat and more upsides due to them being a lizard, without any of the downsides that come with being big

In-Game Examples: Large Lizards can push Onis in 2 shoves, that never miss and pick them up fast in their arms;
Onis miss alot with their shoves on Lizard people, and when a shove connects it rarely matters since their stamina is way better and the next shove attempts will give them time to regain their stamina back;
Even though they are the same size, huge lizard people dont suffer from any aim deviation, unlike Onis extreme aim deviation where some guns (Automatic guns, Prokinetic  gun) where they sometime shoot backwards.

I propose to make onis and large lizards the same level, either onis being better with having aim and better shove/stamina, or making large lizard people weaker compared to Oni due to their aim and being able to drag with their tail, different diet (eating raw meat is really cool, seems very warrior like and in theme with onis, wish onis could eat it too).

I just want Onis boons of combat to actually be an unique thing and for them to matter, other species being a better version of them just gives less and less reasons to be an Oni

**Comment by FoxxoTrystan** [comment]
> After some playful shoving contests, I realized that Onis are overshadowed by large Lizard people in alot of ways when compared to each other.
> 
> Onis whole identity is barely any aim and pure muscles, but its hugely undermined when there's a mutation of a species that overpowers them during close quarter combat and more upsides due to them being a lizard, without any of the downsides that come with being big
> 
> In-Game Examples: Large Lizards can push Onis in 2 shoves, that never miss and pick them up fast in their arms; Onis miss alot with their shoves on Lizard people, and when a shove connects it rarely matters since their stamina is way better and the next shove attempts will give them time to regain their stamina back; Even though they are the same size, huge lizard people dont suffer from any aim deviation, unlike Onis extreme aim deviation where some guns (Automatic guns, Prokinetic gun) where they sometime shoot backwards.
> 
> I propose to make onis and large lizards the same level, either onis being better with having aim and better shove/stamina, or making large lizard people weaker compared to Oni due to their aim and being able to drag with their tail, different diet (eating raw meat is really cool, seems very warrior like and in theme with onis, wish onis could eat it too).
> 
> I just want Onis boons of combat to actually be an unique thing and for them to matter, other species being a better version of them just gives less and less reasons to be an Oni

I will just put this: Bad luck.

Because the weight of Big Lizards and Oni are the same.

ya just have bad RNG.

**Comment by dflttxt** [comment]
> > After some playful shoving contests, I realized that Onis are overshadowed by large Lizard people in alot of ways when compared to each other.
> > Onis whole identity is barely any aim and pure muscles, but its hugely undermined when there's a mutation of a species that overpowers them during close quarter combat and more upsides due to them being a lizard, without any of the downsides that come with being big
> > In-Game Examples: Large Lizards can push Onis in 2 shoves, that never miss and pick them up fast in their arms; Onis miss alot with their shoves on Lizard people, and when a shove connects it rarely matters since their stamina is way better and the next shove attempts will give them time to regain their stamina back; Even though they are the same size, huge lizard people dont suffer from any aim deviation, unlike Onis extreme aim deviation where some guns (Automatic guns, Prokinetic gun) where they sometime shoot backwards.
> > I propose to make onis and large lizards the same level, either onis being better with having aim and better shove/stamina, or making large lizard people weaker compared to Oni due to their aim and being able to drag with their tail, different diet (eating raw meat is really cool, seems very warrior like and in theme with onis, wish onis could eat it too).
> > I just want Onis boons of combat to actually be an unique thing and for them to matter, other species being a better version of them just gives less and less reasons to be an Oni
> 
> I will just put this: Bad luck.
> 
> Because the weight of Big Lizards and Oni are the same.
> 
> ya just have bad RNG.
> 
> And Lizards does not have any bonus from stamina that oni does

>"ya just have bad RNG."

https://github.com/new-frontiers-14/frontier-station-14/assets/143147773/8e51c156-b98d-43b3-b6a3-a842fb344479

**Comment by Hmeister-real** [comment]
Balance idea, just make it so that big lizards can't use any guns in return (and make them shovable too), with the message "Your fingers are too big to fit into the trigger"

**Comment by Mnemotechnician** [comment]
Fixed in #952
