### ISSUE TITLE
Teleporting to 0:0 from any position on map

### ISSUE THREAD

**Issue by Krip4yk-main** [new-frontiers-14/frontier-station-14#923]
## Description
Teleporting to 0:0 (Actually Frontier) from any position on map when taking someone on hands and trying to buckle on cart.

**Reproduction**
Steps:
1) Have any cart (like ATV)
2) Have any live or dead person
3) Take person on hands (Alt+Click with empty hands on person)
4) Move person from hands to cart with mouse
5) Enjoy :)

**Screenshots**
Not required

**Additional context**
 I am fellinid, tested with 2 different persons (dead and alive) and 2 cars on different distance (ATV, Janicart). Leander admin is witness of process.

**Comment by dvir001** [comment]
This been fixed with upstream, the update will be coming
